### ISSUE TITLE
See how the code runs on the backend

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-editor#102]
See how the code runs on the backend and fix bugs

**Comment by Tsogoeva** [comment]
- Пофиксила пару багов, теперь редактор работает корректно.
[ПулРеквест](https://github.com/Hexlet/hexlet-editor/pull/108)

**Может кому пригодится:**
 При запуске проекта столкнулась с ошибкой к подключению к БД:
<img width="787" alt="Снимок экрана 2022-09-10 в 18 34 40" src="https://user-images.githubusercontent.com/52177557/189491830-bfbe1d06-f5a1-4f5d-a315-e67140509440.png">

 Решала её так:
<img width="434" alt="Снимок экрана 2022-09-10 в 18 35 23" src="https://user-images.githubusercontent.com/52177557/189491842-147e7bf7-883f-4a0a-92f4-0085a273a409.png">
