### ISSUE TITLE
Fix a bug. Arithmetic operations do not work

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-editor#114]
Arithmetic operations do not work, such as addition. Check other operations

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/77053797/190907190-e2fa8d0b-7729-4483-952d-8b0bcb0f5cf2.png">

**Comment by Tsogoeva** [comment]
Беру в работу

**Comment by seth2810** [comment]
@dzencot don't forget to close this issue ;)
