### ISSUE TITLE
Replace faker with faker-js

### ISSUE THREAD

**Issue by dzencot** [Hexlet/hexlet-editor#117]

**Comment by MONDAYMIND** [comment]
привет! сориентируйте пожалуйста по этой задаче: нужно удалить старую зависимость и поставить новую + в проекте изменить в местах ее использования? я смогу сделать, если эта зависимость применяется только в кусках кода на js, а если на ts - то не смогу

**Comment by dzencot** [comment]
Привет! Давай так: если будет в ts, то ты хотя бы попытаешься?) Но, вроде, сейчас либа нигде не используется.

**Comment by MONDAYMIND** [comment]
Окей) я вижу, что приоритет стоит у задачи высокий, поэтому решила спросить, вдруг сделать надо срочно, а я ts не знаю) Тогда поменяю библиотеку и проверю по проекту использование

**Comment by MONDAYMIND** [comment]
Зависимость поменяла, да, нигде не используется)
