### ISSUE TITLE
Add page and fix ui

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-editor#125]
1. Create a page "I forgot my password" as https://ru.hexlet.io/remind_password/new
2. Make the layout here http://hexlet-editor.herokuapp.com/signup as here http://hexlet-editor.herokuapp.com/login

**Comment by hawkprimarch** [comment]
Взял в работу

**Comment by Takaiva** [comment]
Сделал пул реквест. Извините, мне теперь объяснили, что надо заранее писать, спрашивать) Это мой первый подобный опыт.

**Comment by hawkprimarch** [comment]
отказываюсь от задачи, решил что приступлю к опен сурс проектам позже
