### ISSUE TITLE
Алиасы

### ISSUE THREAD

**Issue by frontstall** [Hexlet/hexlet-editor#20]
Добавить алиасы для путей, чтобы вместо

```
import { Foo } from '../../../features/';
```
писать
```
import { Foo } from 'features';
```

**Comment by morphizm** [comment]
mokevnin commented 22 days ago
В данном случае игра не стоит свеч. Сломаются все автоматически инструменты, которые не опираются на webpack, так как пути станут не настоящими. А сейчас они очень короткие.

**Comment by jurassic-period** [comment]
Беру эту таску
