### ISSUE TITLE
Внешний вид страницы с редактором

### ISSUE THREAD

**Issue by frontstall** [Hexlet/hexlet-editor#38]
![image](https://user-images.githubusercontent.com/53420091/83685190-ed49eb00-a5f0-11ea-9f97-6c4298fe73f4.png)

Вынести кнопку наверх, сделать отступы

**Comment by MityaDementiy** [comment]
Хочу этот issue сделать.

**Comment by MityaDementiy** [comment]
https://github.com/Hexlet/hexlet-editor/pull/44
