### ISSUE TITLE
Проект не инсталлируется 

### ISSUE THREAD

**Issue by buravlev-arthur** [Hexlet/hexlet-editor#52]
Всяческие конфликты зависимостей при попытке выполнения `make install` и при попытке удаления неподдерживаемых пакетов (например: [optimize-css-assets-webpack-plugin](https://www.npmjs.com/package/optimize-css-assets-webpack-plugin)) и т.д. 

Попытаюсь разобраться.

**Comment by buravlev-arthur** [comment]
Пакет [react-xterm](https://github.com/farfromrefug/react-xterm#readme) требует 15.6.2 (или ниже) версию React. Одновременно даже самая ранняя версия `@reduxjs/toolkit` - 1.0.3 - требует минимум 16 версию React. Ряд других библиотек тоже требуют более новый React, но их версии можно доунгрейдить вручную, а с redux-toolkit тупик.

**Comment by acidmaksim** [comment]
@buravlev-arthur получилось сдвинуться с места?
