### ISSUE TITLE
Make "sign in" page

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-editor#63]

**Comment by acidmaksim** [comment]
There must be two fields 
- Mail;
- Password. 
And 2 buttons:
- Restore Password;
- Registration

When you click on the "Restore Password" button, the "Enter Mail" field and the "Reset Password" button should appear. 
You should receive a link to reset your password. 
After clicking the link, the user should see two fields and one button:
- Password;
- Reset Password;
- Change password (button)

**Comment by Syrupred** [comment]
беру в работу

**Comment by ashikov** [comment]
@Syrupred, привет! Как тут дела?

**Comment by Syrupred** [comment]
@ashikov сегодня отправлю
