### ISSUE TITLE
Make "sign up" page

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-editor#64]

**Comment by acidmaksim** [comment]
Make the registration through the email. There must be 4 fields: 
- Name
- Email
- Password
- Re-password
After that should come a link to the email with confirmation.

**Comment by Sverxsro4nik** [comment]
Беру в работу

**Comment by acidmaksim** [comment]
There must be a validation of the fields. 
The "name" field is a string without digits;
"email" - must be a valid email
"password" - 8 to 30 characters 
"re-password" - is the same as the "password" field
If the "email" field is incorrect, an error should appear - "Incorrect email". 
If you do not enter the password correctly there should be an error - "The password must be 8 to 30 characters long".
There are special libraries for validation.

**Comment by acidmaksim** [comment]
The page can be made similar to this one. 
<img width="1414" alt="image" src="https://user-images.githubusercontent.com/77053797/186112309-3de378fe-5374-4d06-b119-5f7e9b634e9a.png">
