### ISSUE TITLE
Fix bug on JS

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-editor#67]
Now in the editor there is a choice of language - JS.  But it does not work correctly. In the browser console outputs the result, but in the editor console - no. We need to fix this error and make it so that everything is displayed correctly. 

![telegram-cloud-photo-size-2-5467451719966375019-y](https://user-images.githubusercontent.com/77053797/184906141-5d76f94d-c578-48da-9156-444ba1c28b88.jpg)

**Comment by AndreiIlin** [comment]
It cause terminal async thunk used `eval` function and on `console.log` it returns `undefined`

**Comment by Sverxsro4nik** [comment]
Взял в работу

**Comment by ashikov** [comment]
@Sverxsro4nik как дела с этой задачей?

**Comment by Sverxsro4nik** [comment]
Эту задачу пока отложили,  возможно будет изменён терминал

**Comment by AtilMohAmine** [comment]
To solve this problem you can use the node:vm module that provides compiling and running code within V8 Virtual Machine contexts. You can easily catch logs performed in the script runned by the vm.

https://nodejs.org/api/vm.html - Official nodejs/vm
https://github.com/patriksimek/vm2 - Extended vm2

**Comment by AtilMohAmine** [comment]
I can take this work if you want to use this solution

**Comment by ashikov** [comment]
@acidmaksim тут бы привлечь кого-то поревьювить -> #85 PR

**Comment by Sverxsro4nik** [comment]
@ashikov тегни меня в слаке, есть вопрос один, Ярослав не отвечает

**Comment by ashikov** [comment]
У меня +4 часа к Москве. Сегодня уже не на связи. 🙂

**Comment by Sverxsro4nik** [comment]
Давай завтра, у меня плюс 2. Может получится эту задачу решить
