### ISSUE TITLE
Project file tree component

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-editor#71]
use test data for now

**Comment by IvanSavDev** [comment]
Возьму в работу, но хотел предварительно уточнить детали реализации. Необходимо создать компонент, который будет принимать данные по типу:
```
const testData = {
  name: '/',
  children: [
    { name: 'index.js', type: 'file' },
    {
      name: 'App',
      children: [{ name: 'App.js', type: 'file' }],
      type: 'directory',
    },
  ],
  type: 'directory',
};
```

И возвращать соответствующую разметку, что-то похожее как я понял реализовано в упражнениях на основной платформе Hexlet, я верно понял задачу?
И еще вопросов по поводу дизайна, иконки для отображения директорий и файлов использовать на свое усмотрение?

**Comment by acidmaksim** [comment]
@ashikov поможешь?

**Comment by ashikov** [comment]
@mikhaylov-ya тыц

**Comment by mikhaylov-ya** [comment]
@IvanSavDev Привет! Да, ты всё правильно понял, интерфейс данных примерно такой. В плане верстки можно ориентироваться на результаты по запросу в гугле "bootstrap tree view", хотя примеров не так уж и много. Вопрос иконок сейчас не столь важен, на твое усмотрение, важнее добиться минимальной работоспособности.

**Comment by IvanSavDev** [comment]
@mikhaylov-ya Понял, тогда беру в работу
