### ISSUE TITLE
В режиме разработки не собирается проект 

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-editor#82]
Приходится постоянно перезапускать проект, чтобы увидеть изменения, через команду make start. 
Через команду "make frontend" выдает ошибку "Cannot GET /". Что затрудняет разработку

**Comment by acidmaksim** [comment]
@mikhaylov-ya посмотришь, пожалуйста

**Comment by mikhaylov-ya** [comment]
Я так понял, что dev-версия только через nest билдится, то есть через make start-dev. В вебпаке даже нет конфига девсервера, а из папок /dist или /src вебпак ничего сбилдить не может. Я там поигрался, но ничего не получается. @fey глянь тоже, почему make front-dev не работает?

**Comment by mikhaylov-ya** [comment]
Еще я вижу, что эту команду добавила [наша студентка](https://github.com/Hexlet/hexlet-editor/commit/73fdfa4210a40e104af6e4a9dfe3d31e74e5f475), а ее работу ревьюил @dzencot. Мб поможешь разобраться?

**Comment by fey** [comment]
Давай попросим Анастасию помочь @elisad5791

**Comment by IxxyDev** [comment]
Может, имеет смысл сделать отдельные наборы конфигов, package.json'ов и прочего для фронта и бэка?

**Comment by alexandertolchinsky** [comment]
webpack все отдает!  
например файл vendors-node_modules_monaco-editor_esm_vs_language_json_jsonMode_js.js, а файла index у вас нет
нужно на бекенде в режиме разработки менять адрес файлов для фронта

**Comment by alexandertolchinsky** [comment]
временное решение запускать следующую команду npx webpack --watch + make start (в двух терминалах)
завтра где-то в 12 надеюсь найду ошибку
