### ISSUE TITLE
Make a landing

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-editor#90]
Make a landing with a description of the project(https://guides.hexlet.io/ru/how-to-be-a-helpful-for-the-hexlet-community/) and a button that will lead to the editor. 
As an example you can - https://sicp.hexlet.io/ru

**Comment by antonkrupin** [comment]
Возьму в работу эту задачу.
Только не совсем понимаю - лэндинг должен быть вообще отдельный или например его надо добавить как шаблон .pug в папку views?

**Comment by fey** [comment]
@antonkrupin просто страничка в проекте.

**Comment by acidmaksim** [comment]
На странице должно быть описание проекта, картинка, и обязательно кнопка с переходом к редактору. Попробуй сделать по аналогии https://sicp.hexlet.io/ru, только замени картинку)

**Comment by antonkrupin** [comment]
Хорошо. Но блок возможности - я сам не в курсе возможностей редактора =) И где взять ссылку на сам редактор или пока ставить ссылку на репозиторий?

**Comment by acidmaksim** [comment]
У тебя локально запускается проект? Если да, то на странице About должно быть описание проекта, пока можешь взять оттуда. 
Вот ссылка на сам редактор - http://hexlet-editor.herokuapp.com/. Она пока не работает, в процессе починки

**Comment by antonkrupin** [comment]
откажусь от задачи, что то ничего не получается у меня.

**Comment by antonDedyaev** [comment]
@acidmaksim Я возьму в работу.

**Comment by antonDedyaev** [comment]
Привет!) Задача в целом ясна. Немного хотелось бы прояснить техническую реализацию.
Как подтвердил @acidmaksim, страничка должна быть написана и сверстана не на нативном html - вот тут прошу немного подробнее, чтобы двинуться в верном направлении) Очень хочется сделать все по фен-шуй)

**Comment by acidmaksim** [comment]
@mikhaylov-ya подскажи, как лучше поступить и сделать

**Comment by dzencot** [comment]
Делай по шаблонам pug. Как в папке views. В целом там не сложно, если никогда с этим шаблонизатором не работал.

**Comment by antonDedyaev** [comment]
@dzencot Не работал, но уже начал проникаться пока читаю про него :)
Хорошо, спасибо - поработаю с pug.
Готовый лендинг тогда положу потом во views?

**Comment by fey** [comment]
Вы можете сверстать лендинг на чистом html и запушить его. Главное условие - лендинг должен использовать дефолтный бутстрап 5. Потом натянуть на pug будет нетрудно

**Comment by acidmaksim** [comment]
@dzencot а мы разве от пага решили отказываться? Или это к лендигу не относится?

**Comment by fey** [comment]
А для чего уходить от пага? Если про то, что все делать на реакте - ну на паге проще сверстать. Это ж статика. Потом можно переделать.

**Comment by acidmaksim** [comment]
@antonDedyaev как успехи?

**Comment by antonDedyaev** [comment]
@acidmaksim Лендинг уже сделал, запушил. 
По этой задачке все, если других комментариев нет.
