### ISSUE TITLE
Add info about project

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-editor#91]
On page "About"(http://hexlet-editor.herokuapp.com/about) add text:
Hexlet-editor — среда для написания и исполнения кода, которую будем активно использовать на всех платформах Хекслета. Ближайший аналог — сервис repl.it. Бэкенд разрабатывается на NestJS и TypeScript, на фронтенде используется React.

**Comment by abarmenkov** [comment]
возьму в работу
