### ISSUE TITLE
Fix linter & tests

### ISSUE THREAD

**Issue by dzencot** [Hexlet/hexlet-editor#98]
- install eslint plugins
- fix eslint errors
- fix tests (add a simple test for pass)

**Comment by dzencot** [comment]
Plugins for install: eslint-plugin-react, eslint-plugin-jsx-a11y

**Comment by Shamilist** [comment]
Issue at work.

**Comment by Nesaq** [comment]
@dzencot  Привет. С этой задачей все?

**Comment by acidmaksim** [comment]
@dzencot задача закрывать?

**Comment by acidmaksim** [comment]
@dzencot я закрываю эту задачу или нет?

**Comment by dzencot** [comment]
Сорри, пропустил оповещение (буду учиться пользоваться нотификацией гитхаба). Да, я закрою
